// Governed by .rules v1.0
import { Router } from 'express';
import { AdminController } from '../../controllers/admin.controller.js';
import { requireAdmin, requireRole } from '../../middleware/admin.middleware.js';
import { requireAuth } from '../../middleware/auth.middleware.js';
import { UploadController } from '../../controllers/upload.controller.js';
import { uploadLimiter } from '../../middleware/rate-limit.middleware.js';
import { CatalogueController, catalogueCsvUpload } from '../../controllers/catalogue.controller.js';
import { OrderController } from '../../controllers/order.controller.js';
import { PaymentController } from '../../controllers/payment.controller.js';
import { validate } from '../../middleware/validate.middleware.js';
import { idParamSchema } from '../../validators/common.validator.js';
import { orderArchiveSchema, orderPermanentDeleteSchema, orderStatusSchema, refundSchema } from '../../validators/order.validator.js';

export const adminRouter = Router();
adminRouter.use(requireAuth, requireAdmin);
adminRouter.get('/overview', AdminController.overview);
adminRouter.get('/analytics/summary', AdminController.analyticsSummary);
adminRouter.get('/analytics', AdminController.analytics);
adminRouter.get('/orders', OrderController.all);
adminRouter.get('/orders/:id', validate({ params: idParamSchema }), OrderController.adminById);
adminRouter.post('/orders/:id/archive', requireRole(['manager', 'admin', 'superadmin']), validate({ params: idParamSchema, body: orderArchiveSchema }), OrderController.archive);
adminRouter.post('/orders/:id/restore', requireRole(['manager', 'admin', 'superadmin']), validate({ params: idParamSchema }), OrderController.restore);
adminRouter.get('/orders/:id/delete-eligibility', validate({ params: idParamSchema }), OrderController.deleteEligibility);
adminRouter.delete('/orders/:id', requireRole(['superadmin']), validate({ params: idParamSchema, body: orderPermanentDeleteSchema }), OrderController.permanentlyDelete);
adminRouter.patch('/orders/:id/status', requireRole(['manager', 'admin', 'superadmin']), validate({ params: idParamSchema, body: orderStatusSchema }), OrderController.updateStatus);
adminRouter.post('/orders/:id/mark-cod-paid', requireRole(['admin', 'superadmin']), validate({ params: idParamSchema }), OrderController.markCodPaid);
adminRouter.post('/orders/:id/mark-partial-paid', requireRole(['admin', 'superadmin']), validate({ params: idParamSchema }), OrderController.markPartialPaid);
adminRouter.post('/orders/:id/refund', requireRole(['admin', 'superadmin']), validate({ params: idParamSchema, body: refundSchema }), PaymentController.refund);
adminRouter.post('/orders/:id/sync-refund', requireRole(['admin', 'superadmin']), validate({ params: idParamSchema }), OrderController.syncRefund);
adminRouter.get('/uploads/signature', requireRole(['manager', 'admin', 'superadmin']), uploadLimiter, UploadController.signature);
adminRouter.get('/catalogues/dashboard', CatalogueController.dashboard);
adminRouter.post('/catalogues/import/upload', requireRole(['manager', 'admin', 'superadmin']), catalogueCsvUpload.single('file'), CatalogueController.upload);
adminRouter.post('/catalogues/import/preview', requireRole(['manager', 'admin', 'superadmin']), CatalogueController.preview);
adminRouter.post('/catalogues/import/dry-run', requireRole(['manager', 'admin', 'superadmin']), CatalogueController.dryRun);
adminRouter.post('/catalogues/import/confirm', requireRole(['manager', 'admin', 'superadmin']), CatalogueController.confirm);
adminRouter.get('/catalogues/imports', CatalogueController.imports);
adminRouter.get('/catalogues/imports/:id', CatalogueController.importById);
adminRouter.get('/catalogues/imports/:id/errors.csv', CatalogueController.importErrors);
adminRouter.post('/catalogues/export', requireRole(['manager', 'admin', 'superadmin']), CatalogueController.exportCatalogue);
adminRouter.get('/catalogues/exports', CatalogueController.exports);
adminRouter.get('/catalogues/exports/:id/download', CatalogueController.exportDownload);
adminRouter.get('/catalogues/settings', CatalogueController.settings);
adminRouter.patch('/catalogues/settings', requireRole(['manager', 'admin', 'superadmin']), CatalogueController.updateSettings);
