// Governed by .rules v1.0
import { Router } from 'express';
import { AuthController } from '../../controllers/auth.controller.js';
import { requireAuth } from '../../middleware/auth.middleware.js';
import { requireBrowserOrigin } from '../../middleware/browser-origin.middleware.js';
import { authLimiter, otpRequestLimiter, otpVerifyLimiter } from '../../middleware/rate-limit.middleware.js';
import { validate } from '../../middleware/validate.middleware.js';
import { addressBookSchema, addressSchema, forgotPasswordSchema, googleLoginSchema, loginSchema, otpRequestSchema, otpVerifySchema, passwordChangeSchema, preferenceSchema, profileUpdateSchema, refreshSchema, registerSchema, resetPasswordSchema, verifyEmailSchema } from '../../validators/auth.validator.js';
import { idParamSchema } from '../../validators/common.validator.js';

export const authRouter = Router();
authRouter.post('/register', authLimiter, validate({ body: registerSchema }), AuthController.register);
authRouter.post('/login', authLimiter, requireBrowserOrigin, validate({ body: loginSchema }), AuthController.login);
authRouter.post('/refresh', authLimiter, requireBrowserOrigin, validate({ body: refreshSchema }), AuthController.refresh);
authRouter.post('/logout', requireBrowserOrigin, AuthController.logout);
authRouter.post('/google', authLimiter, requireBrowserOrigin, validate({ body: googleLoginSchema }), AuthController.googleLogin);
authRouter.post('/google/admin', authLimiter, requireBrowserOrigin, validate({ body: googleLoginSchema }), AuthController.adminGoogleLogin);
authRouter.post('/otp/request', otpRequestLimiter, validate({ body: otpRequestSchema }), AuthController.requestOtp);
authRouter.post('/otp/verify', otpVerifyLimiter, requireBrowserOrigin, validate({ body: otpVerifySchema }), AuthController.verifyOtp);
authRouter.post('/verify-email', authLimiter, validate({ body: verifyEmailSchema }), AuthController.verifyEmail);
authRouter.post('/forgot-pw', authLimiter, validate({ body: forgotPasswordSchema }), AuthController.forgotPassword);
authRouter.post('/reset-pw', authLimiter, validate({ body: resetPasswordSchema }), AuthController.resetPassword);
authRouter.get('/me', requireAuth, AuthController.me);
authRouter.patch('/me', requireAuth, validate({ body: profileUpdateSchema }), AuthController.updateMe);
authRouter.patch('/me/password', requireAuth, validate({ body: passwordChangeSchema }), AuthController.changePassword);
authRouter.get('/providers', requireAuth, AuthController.providers);
authRouter.post('/providers/link/google', requireAuth, validate({ body: googleLoginSchema }), AuthController.linkGoogleProvider);
authRouter.post('/providers/link/otp', requireAuth, validate({ body: otpVerifySchema }), AuthController.linkOtpProvider);
authRouter.delete('/providers/:id', requireAuth, validate({ params: idParamSchema }), AuthController.unlinkProvider);
authRouter.post('/me/addresses', requireAuth, validate({ body: addressSchema }), AuthController.addAddress);
authRouter.delete('/me/addresses/:id', requireAuth, validate({ params: idParamSchema }), AuthController.removeAddress);
authRouter.get('/addresses', requireAuth, AuthController.addressBook);
authRouter.post('/addresses', requireAuth, validate({ body: addressBookSchema }), AuthController.createAddress);
authRouter.patch('/addresses/:id', requireAuth, validate({ params: idParamSchema, body: addressBookSchema.partial() }), AuthController.updateAddress);
authRouter.delete('/addresses/:id', requireAuth, validate({ params: idParamSchema }), AuthController.deleteAddress);
authRouter.get('/preferences', requireAuth, AuthController.preferences);
authRouter.patch('/preferences', requireAuth, validate({ body: preferenceSchema }), AuthController.updatePreferences);
authRouter.get('/account/dashboard', requireAuth, AuthController.accountDashboard);
authRouter.get('/sessions', requireAuth, AuthController.sessions);
authRouter.delete('/sessions/:id', requireAuth, validate({ params: idParamSchema }), AuthController.revokeSession);
authRouter.delete('/sessions', requireAuth, AuthController.revokeOtherSessions);
authRouter.get('/security/events', requireAuth, AuthController.securityEvents);
authRouter.delete('/me', requireAuth, AuthController.deleteMe);
