// Governed by .rules v1.0
import type { Request, Response } from 'express';
import { env } from '../config/env.js';
import { AuthService } from '../services/auth.service.js';
import { IdentityProviderService } from '../services/identity-provider.service.js';
import { ApiResponse } from '../utils/api-response.js';
import { asyncHandler } from '../utils/async-handler.js';
import { ApiError } from '../utils/api-error.js';

const cookieOptions = {
  httpOnly: true,
  secure: env.NODE_ENV === 'production',
  sameSite: env.COOKIE_SAME_SITE,
  domain: env.COOKIE_DOMAIN,
  path: '/',
  maxAge: 7 * 24 * 60 * 60 * 1000
};
const requestContext = (req: Request): { ipAddress?: string; userAgent?: string; deviceFingerprint?: string } => ({ ipAddress: req.ip, userAgent: req.headers['user-agent'], deviceFingerprint: typeof req.headers['x-device-fingerprint'] === 'string' ? req.headers['x-device-fingerprint'] : undefined });

export const AuthController = {
  register: asyncHandler(async (req: Request<Record<string, string>, unknown, { name: string; email: string; password: string }>, res: Response): Promise<void> => { const user = await AuthService.register(req.body); res.status(201).json(new ApiResponse(user, 'Registration successful. Verify your email.')); }),
  login: asyncHandler(async (req: Request<Record<string, string>, unknown, { email: string; password: string }>, res: Response): Promise<void> => { const result = await AuthService.login(req.body, requestContext(req)); res.cookie('refreshToken', result.tokens.refreshToken, cookieOptions); res.json(new ApiResponse({ user: result.user, accessToken: result.tokens.accessToken }, 'Login successful')); }),
  googleLogin: asyncHandler(async (req: Request<Record<string, string>, unknown, { credential: string }>, res: Response): Promise<void> => { const identity = await IdentityProviderService.verifyGoogleCredential(req.body.credential); const result = await AuthService.googleLogin(identity, requestContext(req)); res.cookie('refreshToken', result.tokens.refreshToken, cookieOptions); res.json(new ApiResponse({ user: result.user, accessToken: result.tokens.accessToken }, 'Google login successful')); }),
  refresh: asyncHandler(async (req: Request, res: Response): Promise<void> => { const refreshToken = typeof req.cookies.refreshToken === 'string' ? req.cookies.refreshToken : ''; if (!refreshToken) throw new ApiError(401, 'Refresh token missing'); const tokens = await AuthService.refresh(refreshToken, requestContext(req)); res.cookie('refreshToken', tokens.refreshToken, cookieOptions); res.json(new ApiResponse({ accessToken: tokens.accessToken }, 'Access token refreshed')); }),
  logout: asyncHandler(async (req: Request, res: Response): Promise<void> => { const refreshToken = typeof req.cookies.refreshToken === 'string' ? req.cookies.refreshToken : ''; if (refreshToken) await AuthService.logout(refreshToken); res.clearCookie('refreshToken', cookieOptions); res.json(new ApiResponse(null, 'Logged out')); }),
  verifyEmail: asyncHandler(async (req: Request<Record<string, string>, unknown, { token: string }>, res: Response): Promise<void> => { await AuthService.verifyEmail(req.body.token); res.json(new ApiResponse(null, 'Email verified')); }),
  forgotPassword: asyncHandler(async (req: Request<Record<string, string>, unknown, { email: string }>, res: Response): Promise<void> => { await AuthService.forgotPassword(req.body.email); res.json(new ApiResponse(null, 'Password reset email sent when account exists')); }),
  resetPassword: asyncHandler(async (req: Request<Record<string, string>, unknown, { token: string; password: string }>, res: Response): Promise<void> => { await AuthService.resetPassword(req.body.token, req.body.password); res.json(new ApiResponse(null, 'Password reset successful')); }),
  requestOtp: asyncHandler(async (req: Request<Record<string, string>, unknown, { phone: string; channel: 'whatsapp'; purpose: 'login' | 'link_account' | 'verify_phone'; deviceFingerprint?: string }>, res: Response): Promise<void> => { const result = await AuthService.requestOtp(req.body, requestContext(req)); res.status(201).json(new ApiResponse(result, 'OTP sent')); }),
  verifyOtp: asyncHandler(async (req: Request<Record<string, string>, unknown, { requestId: string; otp: string; deviceFingerprint?: string }>, res: Response): Promise<void> => { const result = await AuthService.verifyOtp(req.body, requestContext(req)); res.cookie('refreshToken', result.tokens.refreshToken, cookieOptions); res.json(new ApiResponse({ user: result.user, accessToken: result.tokens.accessToken }, 'OTP verified')); }),
  me: asyncHandler(async (req: Request, res: Response): Promise<void> => { if (!req.user) throw new ApiError(401, 'Authentication required'); const user = await AuthService.me(req.user.userId); res.json(new ApiResponse(user, 'Current user')); }),
  updateMe: asyncHandler(async (req: Request<Record<string, string>, unknown, { name?: string; email?: string; phone?: string; avatar?: string; whatsappNumber?: string }>, res: Response): Promise<void> => { if (!req.user) throw new ApiError(401, 'Authentication required'); const user = await AuthService.updateMe(req.user.userId, req.body); res.json(new ApiResponse(user, 'Profile updated')); }),
  changePassword: asyncHandler(async (req: Request<Record<string, string>, unknown, { currentPassword: string; password: string }>, res: Response): Promise<void> => { if (!req.user) throw new ApiError(401, 'Authentication required'); await AuthService.changePassword(req.user.userId, req.body); res.json(new ApiResponse(null, 'Password updated')); }),
  providers: asyncHandler(async (req: Request, res: Response): Promise<void> => { if (!req.user) throw new ApiError(401, 'Authentication required'); const providers = await AuthService.providers(req.user.userId); res.json(new ApiResponse(providers, 'Providers loaded')); }),
  linkGoogleProvider: asyncHandler(async (req: Request<Record<string, string>, unknown, { credential: string }>, res: Response): Promise<void> => { if (!req.user) throw new ApiError(401, 'Authentication required'); const identity = await IdentityProviderService.verifyGoogleCredential(req.body.credential); const provider = await AuthService.linkGoogleProvider(req.user.userId, identity, requestContext(req)); res.status(201).json(new ApiResponse(provider, 'Google provider linked')); }),
  linkOtpProvider: asyncHandler(async (req: Request<Record<string, string>, unknown, { requestId: string; otp: string; deviceFingerprint?: string }>, res: Response): Promise<void> => { if (!req.user) throw new ApiError(401, 'Authentication required'); const provider = await AuthService.linkOtpProvider(req.user.userId, req.body, requestContext(req)); res.status(201).json(new ApiResponse(provider, 'Phone provider linked')); }),
  unlinkProvider: asyncHandler(async (req: Request, res: Response): Promise<void> => { if (!req.user) throw new ApiError(401, 'Authentication required'); await AuthService.unlinkProvider(req.user.userId, String(req.params.id ?? '')); res.json(new ApiResponse(null, 'Provider unlinked')); }),
  addAddress: asyncHandler(async (req: Request<Record<string, string>, unknown, Record<string, unknown>>, res: Response): Promise<void> => { if (!req.user) throw new ApiError(401, 'Authentication required'); const addresses = await AuthService.addAddress(req.user.userId, req.body); res.status(201).json(new ApiResponse(addresses, 'Address added')); }),
  removeAddress: asyncHandler(async (req: Request, res: Response): Promise<void> => { if (!req.user) throw new ApiError(401, 'Authentication required'); const addresses = await AuthService.removeAddress(req.user.userId, String(req.params.id ?? '')); res.json(new ApiResponse(addresses, 'Address removed')); }),
  addressBook: asyncHandler(async (req: Request, res: Response): Promise<void> => { if (!req.user) throw new ApiError(401, 'Authentication required'); const addresses = await AuthService.listAddressBook(req.user.userId); res.json(new ApiResponse(addresses, 'Addresses loaded')); }),
  createAddress: asyncHandler(async (req: Request, res: Response): Promise<void> => { if (!req.user) throw new ApiError(401, 'Authentication required'); const address = await AuthService.createAddressBook(req.user.userId, req.body); res.status(201).json(new ApiResponse(address, 'Address created')); }),
  updateAddress: asyncHandler(async (req: Request, res: Response): Promise<void> => { if (!req.user) throw new ApiError(401, 'Authentication required'); const address = await AuthService.updateAddressBook(req.user.userId, String(req.params.id ?? ''), req.body); res.json(new ApiResponse(address, 'Address updated')); }),
  deleteAddress: asyncHandler(async (req: Request, res: Response): Promise<void> => { if (!req.user) throw new ApiError(401, 'Authentication required'); await AuthService.deleteAddressBook(req.user.userId, String(req.params.id ?? '')); res.json(new ApiResponse(null, 'Address deleted')); }),
  preferences: asyncHandler(async (req: Request, res: Response): Promise<void> => { if (!req.user) throw new ApiError(401, 'Authentication required'); const preferences = await AuthService.preferences(req.user.userId); res.json(new ApiResponse(preferences, 'Preferences loaded')); }),
  updatePreferences: asyncHandler(async (req: Request, res: Response): Promise<void> => { if (!req.user) throw new ApiError(401, 'Authentication required'); const preferences = await AuthService.updatePreferences(req.user.userId, req.body); res.json(new ApiResponse(preferences, 'Preferences updated')); }),
  sessions: asyncHandler(async (req: Request, res: Response): Promise<void> => { if (!req.user) throw new ApiError(401, 'Authentication required'); const sessions = await AuthService.sessions(req.user.userId); res.json(new ApiResponse(sessions, 'Sessions loaded')); }),
  revokeSession: asyncHandler(async (req: Request, res: Response): Promise<void> => { if (!req.user) throw new ApiError(401, 'Authentication required'); await AuthService.revokeSession(req.user.userId, String(req.params.id ?? '')); res.json(new ApiResponse(null, 'Session revoked')); }),
  revokeOtherSessions: asyncHandler(async (req: Request, res: Response): Promise<void> => { if (!req.user) throw new ApiError(401, 'Authentication required'); const refreshToken = typeof req.cookies.refreshToken === 'string' ? req.cookies.refreshToken : undefined; await AuthService.revokeOtherSessions(req.user.userId, refreshToken); res.json(new ApiResponse(null, 'Other sessions revoked')); }),
  securityEvents: asyncHandler(async (req: Request, res: Response): Promise<void> => { if (!req.user) throw new ApiError(401, 'Authentication required'); const events = await AuthService.securityEvents(req.user.userId); res.json(new ApiResponse(events, 'Security events loaded')); }),
  accountDashboard: asyncHandler(async (req: Request, res: Response): Promise<void> => { if (!req.user) throw new ApiError(401, 'Authentication required'); const dashboard = await AuthService.accountDashboard(req.user.userId); res.json(new ApiResponse(dashboard, 'Account dashboard loaded')); }),
  deleteMe: asyncHandler(async (req: Request, res: Response): Promise<void> => { if (!req.user) throw new ApiError(401, 'Authentication required'); await AuthService.deleteMe(req.user.userId); res.clearCookie('refreshToken', cookieOptions); res.json(new ApiResponse(null, 'Account deleted')); })
};
