// Governed by .rules v1.0
'use client';

import { Menu, Search, ShoppingBag, User } from 'lucide-react';
import Link from 'next/link';
import { useEffect, useState, type ReactNode } from 'react';
import { MegaMenu } from '@/components/layout/mega-menu';
import { MobileNav } from '@/components/layout/mobile-nav';
import { SearchModal } from '@/components/shared/search-modal';
import { COPY } from '@/constants/copy';
import { ROUTES } from '@/constants/routes';
import { useCartStore } from '@/store/cartStore';

export interface NavbarProps { }
export function Navbar(_props: NavbarProps): ReactNode { const [scrolled, setScrolled] = useState(false); const [mega, setMega] = useState(false); const [mobile, setMobile] = useState(false); const [search, setSearch] = useState(false); const items = useCartStore((state) => state.items); const openCart = useCartStore((state) => state.openCart); useEffect(() => { const onScroll = (): void => setScrolled(window.scrollY > 8); const onKey = (event: KeyboardEvent): void => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setSearch(true); } }; window.addEventListener('scroll', onScroll); window.addEventListener('keydown', onKey); return () => { window.removeEventListener('scroll', onScroll); window.removeEventListener('keydown', onKey); }; }, []); return <header className={'fixed inset-x-0 top-0 z-50 transition ' + (scrolled ? 'bg-background-elevated/85 backdrop-blur-2xl' : 'bg-transparent')}><a href="#main" className="sr-only focus:not-sr-only">Skip to main content</a><div className="relative mx-auto flex h-14 max-w-[1440px] items-center justify-between px-6 lg:h-16 lg:px-20"><nav className="hidden gap-6 md:flex"><Link onMouseEnter={() => setMega(true)} href={ROUTES.shop} className="text-xs uppercase tracking-[0.12em] text-text-secondary hover:text-text-primary">{COPY.nav.shop}</Link><Link href="/shop?category=outerwear" className="text-xs uppercase tracking-[0.12em] text-text-secondary hover:text-text-primary">{COPY.nav.collections}</Link></nav><button className="md:hidden" aria-label={COPY.nav.menu} onClick={() => setMobile(true)}><Menu size={20} /></button><Link href={ROUTES.home} className="absolute left-1/2 -translate-x-1/2 font-display text-xl text-text-primary">{COPY.brand.name}</Link><div className="flex items-center gap-3"><button aria-label={COPY.nav.search} className="hidden h-11 w-11 items-center justify-center md:flex" onClick={() => setSearch(true)}><Search size={18} /></button><Link aria-label={COPY.nav.account} className="hidden h-11 w-11 items-center justify-center md:flex" href={ROUTES.account}><User size={18} /></Link><button aria-label={COPY.nav.cart} className="relative h-11 w-11" onClick={openCart}><ShoppingBag size={18} />{items.length > 0 ? <span className="absolute right-1 top-1 flex h-5 min-w-5 items-center justify-center bg-accent-gold px-1 font-mono text-[10px] text-text-inverse">{items.length}</span> : null}</button></div></div><div onMouseLeave={() => setMega(false)}><MegaMenu open={mega} /></div><MobileNav open={mobile} onOpenChange={setMobile} /><SearchModal open={search} onOpenChange={setSearch} /></header>; }
