// Governed by .rules v1.0
import type { Product } from '@/types/product.types';

const imageBase = 'https://images.unsplash.com';
export const PRODUCTS: Product[] = [
  { id: 'p1', title: 'Void Drape Hoodie', slug: 'void-drape-hoodie', description: 'Heavyweight cotton fleece with a lowered shoulder and architectural hood.', richDescription: 'Cut oversized with dense brushed cotton, hidden side pockets, and a matte black drawcord system.', brand: 'Cruisin', category: 'Hoodies', images: [{ url: imageBase + '/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=85', alt: 'Model wearing black luxury hoodie', width: 1200, height: 1600 }], basePrice: 18900, comparePrice: 22900, variants: [{ id: 'v1', size: 'S', color: 'Black', colorHex: '#080808', sku: 'CR-VDH-BLK-S', price: 18900, stock: 4, images: [] }, { id: 'v2', size: 'M', color: 'Black', colorHex: '#080808', sku: 'CR-VDH-BLK-M', price: 18900, stock: 0, images: [] }], tags: ['new','editorial'], isFeatured: true, ratings: { avg: 4.8, count: 42 }, seo: { metaTitle: 'Void Drape Hoodie', metaDesc: 'Ultra-premium oversized hoodie by Cruisin.', ogImage: imageBase + '/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=85' }, reviews: [{ id: 'r1', rating: 5, title: 'Insane fabric', body: 'Dense, quiet, and tailored in the right places.', author: 'Aarav', date: '2026-04-18', verified: true }] },
  { id: 'p2', title: 'Signal Cargo Trouser', slug: 'signal-cargo-trouser', description: 'Wide cargo trouser with concealed hardware and fluid stacked break.', richDescription: 'A streetwear trouser built from compact twill with adjustable tabs and deep utility pockets.', brand: 'Cruisin', category: 'Bottoms', images: [{ url: imageBase + '/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=1200&q=85', alt: 'Editorial black cargo trousers', width: 1200, height: 1600 }], basePrice: 16400, variants: [{ id: 'v3', size: '30', color: 'Carbon', colorHex: '#1a1a1a', sku: 'CR-SCT-CBN-30', price: 16400, stock: 8, images: [] }], tags: ['best'], isFeatured: true, ratings: { avg: 4.7, count: 31 }, seo: { metaTitle: 'Signal Cargo Trouser', metaDesc: 'Wide luxury cargo trouser by Cruisin.', ogImage: imageBase + '/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=1200&q=85' }, reviews: [] },
  { id: 'p3', title: 'Afterhours Long Sleeve', slug: 'afterhours-long-sleeve', description: 'Washed jersey long sleeve with tall collar and elongated cuffs.', richDescription: 'A minimal layering piece with a dry hand feel, tonal print, and extended proportions.', brand: 'Cruisin', category: 'Tops', images: [{ url: imageBase + '/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=85', alt: 'Luxury long sleeve editorial look', width: 1200, height: 1600 }], basePrice: 9200, variants: [{ id: 'v4', size: 'L', color: 'Ash', colorHex: '#9a9a9a', sku: 'CR-ALS-ASH-L', price: 9200, stock: 2, images: [] }], tags: ['sale'], isFeatured: false, ratings: { avg: 4.6, count: 18 }, seo: { metaTitle: 'Afterhours Long Sleeve', metaDesc: 'Washed jersey luxury long sleeve by Cruisin.', ogImage: imageBase + '/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=85' }, reviews: [] },
  { id: 'p4', title: 'Monolith Overshirt', slug: 'monolith-overshirt', description: 'Structured overshirt with a precise box fit and hidden placket.', richDescription: 'A transitional outer layer with wool-touch texture, squared hem, and internal pocketing.', brand: 'Cruisin', category: 'Outerwear', images: [{ url: imageBase + '/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=85', alt: 'Minimal black overshirt editorial', width: 1200, height: 1600 }], basePrice: 21400, variants: [{ id: 'v5', size: 'M', color: 'Obsidian', colorHex: '#0f0f0f', sku: 'CR-MO-OBS-M', price: 21400, stock: 6, images: [] }], tags: ['new'], isFeatured: true, ratings: { avg: 4.9, count: 12 }, seo: { metaTitle: 'Monolith Overshirt', metaDesc: 'Structured luxury overshirt by Cruisin.', ogImage: imageBase + '/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=85' }, reviews: [] }
];
export const COLLECTIONS = [{ title: 'Black Transit', href: '/shop?category=outerwear', image: PRODUCTS[3].images[0] }, { title: 'Quiet Uniform', href: '/shop?category=tops', image: PRODUCTS[2].images[0] }, { title: 'Night Cargo', href: '/shop?category=bottoms', image: PRODUCTS[1].images[0] }] as const;
