// Governed by .rules v1.0
export const COPY = {
  brand: { name: 'Cruisin', tagline: 'Wear Less. Mean More.', label: 'Ultra premium streetwear' },
  nav: { shop: 'Shop', collections: 'Collections', journal: 'Journal', account: 'Account', cart: 'Cart', search: 'Search', menu: 'Menu', close: 'Close', wishlist: 'Wishlist', home: 'Home' },
  home: { featured: 'Featured Collections', bestSellers: 'Best Sellers', flashSale: 'Private Window', newArrivals: 'New Arrivals', instagram: 'Seen In Motion', newsletter: 'Join The List', newsletterBody: 'Private drops, early access, and nothing unnecessary.', email: 'Email address', subscribe: 'Subscribe', success: 'You are on the list.', error: 'Something slipped. Try again.' },
  shop: { title: 'Shop All', eyebrow: 'Private Catalogue', filters: 'Filters', sort: 'Sort', loadMore: 'Load More', grid: 'Grid', list: 'List', showing: 'Showing', items: 'items', emptyTitle: 'Nothing Fits The Mood', emptyCta: 'Clear Filters', quickAdd: 'Quick Add', add: 'Add To Cart', soldOut: 'Sold Out', new: 'New', sale: 'Sale' },
  filters: { sizes: ['XS', 'S', 'M', 'L', 'XL', '30', '32', '34'], colors: ['Black', 'Ash', 'Carbon', 'Oatmeal', 'Espresso', 'Sage Green', 'Stealth Black', 'Grey', 'Charcoal', 'White', 'Sand'] },
  product: { size: 'Size', color: 'Color', sizeGuide: 'Size Guide', add: 'Add To Cart', selectSize: 'Select a size', onlyLeft: 'Only {count} left', description: 'Description', shipping: 'Shipping & Returns', reviews: 'Reviews', leaveReview: 'Leave A Review', recommended: 'Recommended', recentlyViewed: 'Recently Viewed', share: 'Share', copied: 'Link copied', wishlist: 'Toggle wishlist' },
  cart: { title: 'Bag', emptyTitle: 'Your Bag Is Quiet', emptyBody: 'A deliberate wardrobe starts with one piece.', continue: 'Continue Shopping', subtotal: 'Subtotal', discount: 'Discount', shipping: 'Shipping', tax: 'Taxes', taxIncluded: 'Included', total: 'Total', coupon: 'Coupon code', apply: 'Apply', checkout: 'Proceed To Checkout', remove: 'Remove', undo: 'Undo', freeShipping: 'more for complimentary shipping', stockAvailable: '{count} available', stockLimit: 'All available stock is already in your bag' },
  checkout: {
    title: 'Checkout',
    eyebrow: 'Secure Private Client Flow',
    body: 'Every field is deliberate. Every shipment is handled with the calm of a private appointment.',
    info: 'Info',
    shipping: 'Shipping',
    payment: 'Payment',
    address: 'Address',
    methods: 'Shipping Method',
    paymentMethod: 'Payment Method',
    placeOrder: 'Place Order',
    completePayment: 'Complete Payment',
    success: 'Order Confirmed',
    onlineConfirmed: 'Payment confirmed.',
    codConfirmed: 'Order placed — {amount} is due on delivery.',
    partialConfirmed: 'Advance payment of {paid} received; {due} remains due.',
    failure: 'Payment Failed',
    failureBody: 'Your payment was not completed. No wardrobe decision should be lost to a bad network moment.',
    retry: 'Retry Payment',
    pending: 'Payment Verification Pending',
    pendingBody: 'We have not marked this order as paid yet. This page checks the verified server status automatically.',
    pendingHint: 'You can safely leave this page and review the same status in My Orders.',
    pendingOrder: 'Order pending',
    statusUnavailable: 'We could not load the latest payment status. Open My Orders to check again.',
    viewOrder: 'View order details',
    myOrders: 'My orders',
    providers: { razorpay: 'Razorpay', stripe: 'Stripe' },
    shippingOptions: { standard: 'Standard', express: 'Express' },
    confirmation: {
      eyebrow: 'Order complete',
      items: 'Items',
      delivery: 'Delivery',
      payment: 'Payment',
      purchasedItems: 'Purchased items',
      orderSummary: 'Order summary',
      deliveryAddress: 'Delivery address',
      next: 'What happens next',
      orderRecorded: 'Order recorded',
      orderRecordedBody: 'Your order is safely stored in your Cruisin account.',
      preparation: 'Preparation',
      preparationBody: 'The team will prepare your pieces and update the order timeline.',
      tracking: 'Tracking after dispatch',
      trackingBody: 'Your tracking number will appear in order details when the parcel leaves.',
      merchandise: 'Merchandise subtotal',
      discount: 'Discount',
      standardDelivery: 'Standard delivery',
      expressDelivery: 'Express delivery',
      tax: 'Tax',
      codFee: 'Cash on delivery fee',
      total: 'Order total',
      paid: 'Paid',
      due: 'Balance due',
      cashOnDelivery: 'Cash on delivery',
      partialPayment: 'Advance payment',
      onlinePayment: 'Online payment',
      addressUnavailable: 'The delivery address is available in order details.',
      originalVariant: 'Selected variant',
      quantity: 'Qty'
    }
  },
  fields: { label: 'Label', fullName: 'Full name', phone: 'Phone', whatsapp: 'WhatsApp number', city: 'City', state: 'State', postalCode: 'Postal code', country: 'Country', street: 'Street', landmark: 'Landmark', addressType: 'Address type', defaultCountry: 'India' },
  auth: {
    login: 'Login',
    register: 'Register',
    signIn: 'Sign in',
    createAccount: 'Create account',
    myAccount: 'My account',
    privateAccess: 'Private client access',
    checkingSession: 'Checking your private client access...',
    newClient: 'New to Cruisin?',
    existingClient: 'Already a private client?',
    forgot: 'Forgot Password',
    reset: 'Reset Password',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    name: 'Name',
    submit: 'Continue',
    logout: 'Sign out',
    token: 'Reset token',
    resetSent: 'If the account exists, a reset link is on its way.',
    resetComplete: 'Password reset complete.',
    emailMethod: 'Email',
    whatsappMethod: 'WhatsApp OTP',
    googleMethod: 'Continue with Google',
    requestOtp: 'Send Code',
    verifyOtp: 'Verify Code',
    otp: 'Verification code',
    otpSent: 'A six digit code was sent.',
    developmentCode: 'Development code',
    providerUnavailable: 'Provider is not configured yet.',
    whatsapp: {
      eyebrow: 'Fast, password-free access',
      continue: 'Continue with WhatsApp',
      intro: 'Enter your WhatsApp number. We will sign you in—or create your account automatically if you are new.',
      countryCode: 'Code',
      phone: 'WhatsApp number',
      phonePlaceholder: '98765 43210',
      sendCode: 'Send code on WhatsApp',
      codeSent: 'Code sent on WhatsApp. It expires in 5 minutes.',
      changeNumber: 'Change number',
      resendCode: 'Resend code',
      resendCodeIn: 'Resend code in {seconds}s',
      useAlternatives: 'Use email or Google',
      useWhatsAppInstead: 'Use WhatsApp OTP instead',
      alternativesLabel: 'Email authentication',
      alternativesTitle: 'Use email or Google',
      consentPrefix: 'By continuing, you agree to Cruisin’s',
      terms: 'terms',
      privacy: 'privacy policy'
    },
    prompts: {
      checkout: { title: 'Continue securely', body: 'Use your WhatsApp number to sign in or create your account in one step. Your cart will be waiting.', dismiss: 'Continue shopping' },
      wishlist: { title: 'Save this piece', body: 'Continue with WhatsApp to save favourites and access them across devices.', dismiss: 'Not now' },
      orders: { title: 'View your orders', body: 'Continue with WhatsApp to access your private order history and delivery updates.', dismiss: 'Continue shopping' }
    }
  },
  account: { title: 'Account', eyebrow: 'Private Client', profile: 'Profile', orders: 'Orders', wishlist: 'Wishlist', addresses: 'Addresses', security: 'Security', notifications: 'Notifications', preferences: 'Preferences', membership: 'Membership', recentOrders: 'Recent Orders', rewardPoints: 'Reward Points', savedAddresses: 'Saved Addresses', securityEvents: 'Security Events', connectedAccounts: 'Connected Accounts', activeSessions: 'Active Sessions', deviceHistory: 'Device History', logoutOthers: 'Logout Other Devices', revoke: 'Revoke', linked: 'Connected', notLinked: 'Not Connected', noOrders: 'No recent orders yet.', noNotifications: 'Nothing needs your attention.', noEvents: 'No security events yet.', noSessions: 'No active sessions found.', marketingEmails: 'Marketing emails', orderEmails: 'Order and delivery emails', pushNotifications: 'In-app notifications', smsNotifications: 'SMS notifications', whatsappNotifications: 'WhatsApp notifications', language: 'Language', currency: 'Currency', home: 'Home', office: 'Office', other: 'Other', default: 'Default', delete: 'Delete Account', save: 'Save Changes', saved: 'Changes saved' },
  admin: { title: 'Dashboard', overview: 'Overview', products: 'Products', orders: 'Orders', users: 'Users', categories: 'Categories', discounts: 'Discounts', cms: 'CMS', analytics: 'Analytics', revenue: 'Revenue', conversion: 'Conversion', export: 'Export CSV', create: 'Create', search: 'Search', confirm: 'Confirm', cancel: 'Cancel' },
  common: { processing: 'Processing...', loading: 'Loading', error: 'Something went wrong', retry: 'Retry', notFound: 'Page Not Found', backHome: 'Back Home', open: 'Open', close: 'Close', or: 'Or', and: 'and' }
} as const;
