// Governed by .rules v1.0
export const COPY = {
  brand: { name: 'Cruisin', tagline: 'Wear Less. Mean More.', label: 'Ultra premium streetwear' },
  nav: { shop: 'Shop', collections: 'Collections', journal: 'Journal', account: 'Account', cart: 'Cart', search: 'Search', menu: 'Menu', close: 'Close', wishlist: 'Wishlist', home: 'Home' },
  hero: { eyebrow: 'Drop 04 / Black Transit', lineOne: 'Wear Less.', lineTwo: 'Mean More.', cta: 'Enter The Drop', secondary: 'View Lookbook', scroll: 'Scroll' },
  home: { featured: 'Featured Collections', bestSellers: 'Best Sellers', flashSale: 'Private Window', newArrivals: 'New Arrivals', instagram: 'Seen In Motion', newsletter: 'Join The List', newsletterBody: 'Private drops, early access, and nothing unnecessary.', email: 'Email address', subscribe: 'Subscribe', success: 'You are on the list.', error: 'Something slipped. Try again.' },
  shop: { title: 'Shop All', eyebrow: 'Private Catalogue', filters: 'Filters', sort: 'Sort', loadMore: 'Load More', grid: 'Grid', list: 'List', showing: 'Showing', items: 'items', emptyTitle: 'Nothing Fits The Mood', emptyCta: 'Clear Filters', quickAdd: 'Quick Add', add: 'Add To Cart', soldOut: 'Sold Out', new: 'New', sale: 'Sale' },
  filters: { sizes: ['XS', 'S', 'M', 'L', 'XL', '30', '32', '34'], colors: ['Black', 'Ash', 'Carbon', 'Oatmeal', 'Espresso', 'Sage Green', 'Stealth Black', 'Grey', 'Charcoal', 'White', 'Sand'] },
  product: { size: 'Size', color: 'Color', sizeGuide: 'Size Guide', add: 'Add To Cart', selectSize: 'Select a size', onlyLeft: 'Only {count} left', description: 'Description', shipping: 'Shipping & Returns', reviews: 'Reviews', leaveReview: 'Leave A Review', recommended: 'Recommended', recentlyViewed: 'Recently Viewed', share: 'Share', copied: 'Link copied', wishlist: 'Toggle wishlist' },
  cart: { title: 'Bag', emptyTitle: 'Your Bag Is Quiet', emptyBody: 'A deliberate wardrobe starts with one piece.', continue: 'Continue Shopping', subtotal: 'Subtotal', discount: 'Discount', shipping: 'Shipping', tax: 'Tax', total: 'Total', coupon: 'Coupon code', apply: 'Apply', checkout: 'Proceed To Checkout', remove: 'Remove', undo: 'Undo', freeShipping: 'more for complimentary shipping' },
  checkout: { title: 'Checkout', eyebrow: 'Secure Private Client Flow', body: 'Every field is deliberate. Every shipment is handled with the calm of a private appointment.', info: 'Info', shipping: 'Shipping', payment: 'Payment', address: 'Address', methods: 'Shipping Method', paymentMethod: 'Payment Method', placeOrder: 'Place Order', completePayment: 'Complete Payment', success: 'Order Confirmed', failure: 'Payment Failed', failureBody: 'Your payment was not completed. No wardrobe decision should be lost to a bad network moment.', retry: 'Retry Payment', pendingOrder: 'Order pending', providers: { razorpay: 'Razorpay', stripe: 'Stripe' }, shippingOptions: { standard: 'Standard · ₹900', express: 'Express · ₹1800' } },
  fields: { label: 'Label', fullName: 'Full name', phone: 'Phone', city: 'City', state: 'State', postalCode: 'Postal code', country: 'Country', defaultCountry: 'India' },
  auth: { login: 'Login', register: 'Register', forgot: 'Forgot Password', reset: 'Reset Password', email: 'Email', password: 'Password', confirmPassword: 'Confirm Password', name: 'Name', submit: 'Continue', logout: 'Logout', token: 'Reset token', resetSent: 'If the account exists, a reset link is on its way.', resetComplete: 'Password reset complete.' },
  account: { title: 'Account', profile: 'Profile', orders: 'Orders', wishlist: 'Wishlist', addresses: 'Addresses', delete: 'Delete Account', save: 'Save Changes', saved: 'Changes saved' },
  admin: { title: 'Dashboard', overview: 'Overview', products: 'Products', orders: 'Orders', users: 'Users', categories: 'Categories', discounts: 'Discounts', cms: 'CMS', analytics: 'Analytics', revenue: 'Revenue', conversion: 'Conversion', export: 'Export CSV', create: 'Create', search: 'Search', confirm: 'Confirm', cancel: 'Cancel' },
  common: { processing: 'Processing...', loading: 'Loading', error: 'Something went wrong', retry: 'Retry', notFound: 'Page Not Found', backHome: 'Back Home', open: 'Open', close: 'Close' }
} as const;
