export const RETURN_EXCHANGE_COPY = {
  checking: 'Checking delivery eligibility…',
  unavailable: 'Delivery confirmation is unavailable. Please try again shortly.',
  checkingButton: 'Checking eligibility',
  unavailableButton: 'Delivery confirmation unavailable',
  beforeDelivery: 'Returns and exchanges become available after courier-confirmed delivery.',
  afterDeliveryButton: 'Available after delivery',
  cancelled: 'Returns and exchanges are unavailable for cancelled orders.',
  cancelledButton: 'Order cancelled',
  expired: 'The 5-day return and exchange window has ended.',
  expiredButton: 'Window closed',
  requestButton: 'Return or exchange',
  exchangesHeading: 'Exchange requests',
  exchangeRequest: 'Exchange request',
  replacement: 'Replacement SKU',
  originalOrder: 'Original order',
  updated: 'Latest update',
  submitted: 'Submitted',
  historyTitle: 'My returns & exchanges',
  historyDescription: 'Payment, review, pickup, refund and replacement progress for your requests.',
  emptyTitle: 'No return or exchange requests',
  emptyDescription: 'Eligible delivered orders show a Return or exchange option in order details.',
} as const;
